import React, { useState, useEffect } from 'react';
import { FileText, Download, Search, Calendar, User as UserIcon, CreditCard, Printer, CheckCircle, XCircle } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { QRCodeSVG } from 'qrcode.react';

export default function Reports() {
  const { user } = useAuth();
  const [tickets, setTickets] = useState<any[]>([]);
  const [totalTickets, setTotalTickets] = useState(0);
  const [ticketPage, setTicketPage] = useState(1);
  const [filteredTickets, setFilteredTickets] = useState<any[]>([]);
  const [userStats, setUserStats] = useState<any[]>([]);
  const [totalUserStats, setTotalUserStats] = useState(0);
  const [userStatsPage, setUserStatsPage] = useState(1);
  const [myReports, setMyReports] = useState<any[]>([]);
  const [totalMyReports, setTotalMyReports] = useState(0);
  const [myReportsPage, setMyReportsPage] = useState(1);
  const [searchTerm, setSearchTerm] = useState('');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [selectedCampaign, setSelectedCampaign] = useState('');
  const [selectedMonth, setSelectedMonth] = useState('');
  const [campaigns, setCampaigns] = useState<any[]>([]);
  const [activeView, setActiveView] = useState<'all' | 'user-stats' | 'my-reports'>(user?.role === 'Admin' ? 'all' : 'my-reports');
  const [selectedTicket, setSelectedTicket] = useState<any>(null);

  useEffect(() => {
    fetch('/api/campaigns', { headers: { 'Authorization': `Bearer ${localStorage.getItem('kartal_token')}` } })
      .then(res => res.json().catch(() => []))
      .then(data => setCampaigns(Array.isArray(data) ? data : []))
      .catch(() => setCampaigns([]));
  }, []);

  useEffect(() => {
    const headers = { 'Authorization': `Bearer ${localStorage.getItem('kartal_token')}` };
    if (user?.role === 'Admin') {
      if (activeView === 'all') {
        fetch(`/api/tickets?page=${ticketPage}&search=${searchTerm}&startDate=${dateFrom}&endDate=${dateTo}&campaignId=${selectedCampaign}&month=${selectedMonth}`, { headers })
          .then(res => res.json().catch(() => ({ tickets: [], totalCount: 0 })))
          .then(data => {
            setTickets(Array.isArray(data.tickets) ? data.tickets : []);
            setTotalTickets(data.totalCount || 0);
            setFilteredTickets(Array.isArray(data.tickets) ? data.tickets : []);
          })
          .catch(() => {
            setTickets([]);
            setFilteredTickets([]);
          });
      }
      
      if (activeView === 'user-stats') {
        fetch(`/api/reports/user-stats?page=${userStatsPage}`, { headers })
          .then(res => res.json().catch(() => ({ stats: [], totalCount: 0 })))
          .then(data => {
            setUserStats(Array.isArray(data.stats) ? data.stats : []);
            setTotalUserStats(data.totalCount || 0);
          })
          .catch(() => setUserStats([]));
      }
    } else {
      fetch(`/api/reports/user/${user?.email}?startDate=${dateFrom}&endDate=${dateTo}&page=${myReportsPage}`, { headers })
        .then(res => res.json().catch(() => ({ reports: [], totalCount: 0 })))
        .then(data => {
          setMyReports(Array.isArray(data.reports) ? data.reports : []);
          setTotalMyReports(data.totalCount || 0);
        })
        .catch(() => {
          setMyReports([]);
          setTotalMyReports(0);
        });
    }
  }, [user, activeView, ticketPage, userStatsPage, myReportsPage, searchTerm, dateFrom, dateTo]);

  const maskMobile = (mobile: string) => {
    if (!mobile) return '';
    return mobile.slice(0, -3) + '***';
  };

  const exportToCSV = () => {
    try {
      let headers: string[] = [];
      let rows: any[][] = [];
      let filename = '';

      if (activeView === 'all') {
        headers = ['Ticket ID', 'Tx ID', 'Customer Name', 'Mobile', 'Address', 'Amount', 'Payment Type', 'Generated By', 'Date'];
        rows = filteredTickets.map(t => [
          `"${t.ticket_id}"`,
          `"${t.tx_id}"`,
          `"${(t.name || '').replace(/"/g, '""')}"`,
          `"${(t.mobile || '').replace(/"/g, '""')}"`,
          `"${(t.address || 'N/A').replace(/"/g, '""')}"`,
          t.amount / t.total_tickets_in_tx,
          `"${t.payment_type}"`,
          `"${(t.generated_by_nick || t.generated_by || '').replace(/"/g, '""')}"`,
          `"${new Date(t.date).toLocaleString()}"`
        ]);
        filename = `tickets_report_${new Date().toISOString().slice(0,10)}.csv`;
      } else if (activeView === 'user-stats') {
        headers = ['User', 'Nick Name', 'Today Tickets', 'Month Tickets', 'Today Revenue', 'Month Revenue'];
        rows = userStats.map(s => [
          `"${(s.name || s.email || '').replace(/"/g, '""')}"`,
          `"${(s.nick_name || '').replace(/"/g, '""')}"`,
          s.today_count,
          s.month_count,
          s.today_revenue,
          s.month_revenue
        ]);
        filename = `user_stats_${new Date().toISOString().slice(0,10)}.csv`;
      } else {
        headers = ['Tx ID', 'Ticket ID', 'Amount', 'Date', 'Status', 'Printed'];
        rows = myReports.map(r => [
          `"${r.tx_id}"`,
          `"${r.ticket_id || ''}"`,
          r.amount,
          `"${new Date(r.date).toLocaleDateString()}"`,
          `"${r.status}"`,
          r.printed_count > 0 ? 'Yes' : 'No'
        ]);
        filename = `my_activity_${new Date().toISOString().slice(0,10)}.csv`;
      }

      const csvContent = [
        headers.join(','),
        ...rows.map(r => r.join(','))
      ].join('\n');

      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', filename);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Export failed:', err);
    }
  };

  useEffect(() => {
    let filtered = tickets;

    if (searchTerm) {
      const term = searchTerm.toLowerCase();
      filtered = filtered.filter(t => 
        (t.ticket_id?.toLowerCase() || '').includes(term) ||
        (t.tx_id?.toLowerCase() || '').includes(term) ||
        (t.name?.toLowerCase() || '').includes(term) ||
        (t.mobile?.toLowerCase() || '').includes(term) ||
        (t.generation_id?.toLowerCase() || '').includes(term)
      );
    }

    if (dateFrom) {
      filtered = filtered.filter(t => new Date(t.date) >= new Date(dateFrom));
    }

    if (dateTo) {
      const toDate = new Date(dateTo);
      toDate.setHours(23, 59, 59, 999);
      filtered = filtered.filter(t => new Date(t.date) <= toDate);
    }

    setFilteredTickets(filtered);
  }, [searchTerm, dateFrom, dateTo, tickets]);

  return (
    <div className="max-w-7xl mx-auto space-y-8 pb-12">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Kartal Group Reports</h1>
          <p className="mt-1 text-gray-500">Comprehensive analytics and transaction history.</p>
          {dateFrom && new Date(dateFrom) < new Date(new Date().setHours(0,0,0,0)) && (
            <div className="mt-3 inline-flex items-center px-3 py-1 rounded-full text-xs font-bold bg-emerald-50 text-emerald-700 border border-emerald-100">
              <CheckCircle className="w-3 h-3 mr-1" /> Finalized Report
            </div>
          )}
        </div>
        <div className="flex flex-wrap items-center gap-4">
          <div className="flex bg-gray-100 p-1 rounded-xl">
            {user?.role === 'Admin' ? (
              <>
                <button
                  onClick={() => setActiveView('all')}
                  className={`px-4 py-2 text-sm font-bold rounded-lg transition-all ${
                    activeView === 'all' ? 'bg-white text-indigo-600 shadow-sm' : 'text-gray-500 hover:text-gray-700'
                  }`}
                >
                  All Tickets
                </button>
                <button
                  onClick={() => setActiveView('user-stats')}
                  className={`px-4 py-2 text-sm font-bold rounded-lg transition-all ${
                    activeView === 'user-stats' ? 'bg-white text-indigo-600 shadow-sm' : 'text-gray-500 hover:text-gray-700'
                  }`}
                >
                  User Stats
                </button>
              </>
            ) : (
              <button className="px-4 py-2 text-sm font-bold rounded-lg bg-white text-indigo-600 shadow-sm">
                My Activity
              </button>
            )}
          </div>
          {user?.role === 'Admin' && (
            <button 
              onClick={exportToCSV}
              className="inline-flex items-center px-6 py-2 bg-white border border-gray-200 shadow-sm text-sm font-bold rounded-xl text-gray-700 hover:bg-gray-50 transition-all"
            >
              <Download className="w-4 h-4 mr-2" />
              Export
            </button>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-white p-6 rounded-3xl border border-gray-100 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="p-2 bg-indigo-50 rounded-xl">
              <FileText className="w-5 h-5 text-indigo-600" />
            </div>
          </div>
          <p className="text-sm font-bold text-gray-400 uppercase tracking-wider">Total Tickets</p>
          <p className="text-3xl font-black text-gray-900 mt-1">{filteredTickets.length}</p>
        </div>
        <div className="bg-white p-6 rounded-3xl border border-gray-100 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="p-2 bg-emerald-50 rounded-xl">
              <CreditCard className="w-5 h-5 text-emerald-600" />
            </div>
          </div>
          <p className="text-sm font-bold text-gray-400 uppercase tracking-wider">Total Revenue</p>
          <p className="text-3xl font-black text-gray-900 mt-1">
            PKR {filteredTickets.reduce((acc, t) => acc + (t.amount / t.total_tickets_in_tx), 0).toLocaleString()}
          </p>
        </div>
        <div className="bg-white p-6 rounded-3xl border border-gray-100 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="p-2 bg-blue-50 rounded-xl">
              <CheckCircle className="w-5 h-5 text-blue-600" />
            </div>
          </div>
          <p className="text-sm font-bold text-gray-400 uppercase tracking-wider">Cash Revenue</p>
          <p className="text-3xl font-black text-gray-900 mt-1">
            PKR {filteredTickets.filter(t => t.payment_type === 'CASH').reduce((acc, t) => acc + (t.amount / t.total_tickets_in_tx), 0).toLocaleString()}
          </p>
        </div>
        <div className="bg-white p-6 rounded-3xl border border-gray-100 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="p-2 bg-purple-50 rounded-xl">
              <Printer className="w-5 h-5 text-purple-600" />
            </div>
          </div>
          <p className="text-sm font-bold text-gray-400 uppercase tracking-wider">Online Revenue</p>
          <p className="text-3xl font-black text-gray-900 mt-1">
            PKR {filteredTickets.filter(t => t.payment_type === 'ONLINE').reduce((acc, t) => acc + (t.amount / t.total_tickets_in_tx), 0).toLocaleString()}
          </p>
        </div>
      </div>

      {activeView === 'all' ? (
        <>
          <div className="bg-white p-6 rounded-3xl border border-gray-100 shadow-sm space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              <div className="relative">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                <input
                  type="text"
                  placeholder="Search by ID, Name, Mobile..."
                  value={searchTerm}
                  onChange={(e) => { setSearchTerm(e.target.value); setTicketPage(1); }}
                  className="pl-12 w-full rounded-2xl border-gray-200 border p-3 text-sm focus:ring-2 focus:ring-indigo-500 transition-all outline-none"
                />
              </div>
              <div className="flex items-center gap-3">
                <div className="flex-1 relative">
                  <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                  <input
                    type="date"
                    value={dateFrom}
                    onChange={(e) => { setDateFrom(e.target.value); setTicketPage(1); }}
                    className="pl-10 w-full rounded-xl border-gray-200 border p-2 text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
                  />
                </div>
                <span className="text-gray-400 font-bold">to</span>
                <div className="flex-1 relative">
                  <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                  <input
                    type="date"
                    value={dateTo}
                    onChange={(e) => { setDateTo(e.target.value); setTicketPage(1); }}
                    className="pl-10 w-full rounded-xl border-gray-200 border p-2 text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
                  />
                </div>
              </div>
              <div className="flex items-center gap-3">
                <select
                  value={selectedCampaign}
                  onChange={(e) => { setSelectedCampaign(e.target.value); setTicketPage(1); }}
                  className="flex-1 rounded-xl border-gray-200 border p-2 text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
                >
                  <option value="">All Campaigns</option>
                  {campaigns.map(c => (
                    <option key={c.id} value={c.id}>{c.name}</option>
                  ))}
                </select>
                <input
                  type="month"
                  value={selectedMonth}
                  onChange={(e) => { setSelectedMonth(e.target.value); setTicketPage(1); }}
                  className="flex-1 rounded-xl border-gray-200 border p-2 text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
                />
              </div>
            </div>
          </div>
          <div className="bg-white rounded-3xl border border-gray-100 shadow-sm overflow-hidden">
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-100">
                <thead className="bg-gray-50/50">
                  <tr>
                    <th className="px-6 py-4 text-left text-xs font-bold text-gray-400 uppercase tracking-wider">Ticket ID</th>
                    <th className="px-6 py-4 text-left text-xs font-bold text-gray-400 uppercase tracking-wider">Customer</th>
                    <th className="px-6 py-4 text-left text-xs font-bold text-gray-400 uppercase tracking-wider">Created By</th>
                    <th className="px-6 py-4 text-left text-xs font-bold text-gray-400 uppercase tracking-wider">Printed By</th>
                    <th className="px-6 py-4 text-left text-xs font-bold text-gray-400 uppercase tracking-wider">Date/Time</th>
                    <th className="px-6 py-4 text-right text-xs font-bold text-gray-400 uppercase tracking-wider">Details</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-50">
                  {tickets.map((ticket) => (
                    <tr key={ticket.id} className="hover:bg-gray-50/50 transition-colors">
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-bold text-indigo-600">{ticket.ticket_id}</div>
                        <div className="text-[10px] text-gray-400 font-mono">Tx: {ticket.tx_id}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-bold text-gray-900">{ticket.name}</div>
                        <div className="text-xs text-gray-500">{maskMobile(ticket.mobile)}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-xs text-gray-900 font-bold">{ticket.generated_by_nick || ticket.generated_by}</div>
                        <div className="text-[10px] text-gray-400">{new Date(ticket.date).toLocaleDateString()}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-xs text-gray-900 font-bold">{ticket.last_printed_by_nick || '-'}</div>
                        {ticket.last_printed_at && <div className="text-[10px] text-gray-400">{new Date(ticket.last_printed_at).toLocaleDateString()}</div>}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {new Date(ticket.date).toLocaleString()}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <button 
                          onClick={() => setSelectedTicket(ticket)}
                          className="px-4 py-2 bg-indigo-50 text-indigo-600 rounded-xl font-bold hover:bg-indigo-100 transition-all"
                        >
                          View
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            
            {/* Pagination */}
            <div className="px-6 py-4 bg-gray-50/50 border-t border-gray-100 flex items-center justify-between">
              <div className="text-sm text-gray-500">
                Showing <span className="font-bold">{(ticketPage - 1) * 20 + 1}</span> to <span className="font-bold">{Math.min(ticketPage * 20, totalTickets)}</span> of <span className="font-bold">{totalTickets}</span> tickets
              </div>
              <div className="flex gap-2">
                <button 
                  disabled={ticketPage === 1}
                  onClick={() => setTicketPage(prev => prev - 1)}
                  className="px-4 py-2 bg-white border border-gray-200 rounded-xl text-sm font-bold disabled:opacity-50 hover:bg-gray-50 transition-all"
                >
                  Previous
                </button>
                <button 
                  disabled={ticketPage * 20 >= totalTickets}
                  onClick={() => setTicketPage(prev => prev + 1)}
                  className="px-4 py-2 bg-white border border-gray-200 rounded-xl text-sm font-bold disabled:opacity-50 hover:bg-gray-50 transition-all"
                >
                  Next
                </button>
              </div>
            </div>
          </div>
        </>
      ) : activeView === 'user-stats' ? (
        <div className="bg-white rounded-3xl border border-gray-100 shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-100">
              <thead className="bg-gray-50/50">
                <tr>
                  <th className="px-6 py-4 text-left text-xs font-bold text-gray-400 uppercase tracking-wider">User</th>
                  <th className="px-6 py-4 text-left text-xs font-bold text-gray-400 uppercase tracking-wider">Today (Tickets)</th>
                  <th className="px-6 py-4 text-left text-xs font-bold text-gray-400 uppercase tracking-wider">Month (Tickets)</th>
                  <th className="px-6 py-4 text-left text-xs font-bold text-gray-400 uppercase tracking-wider">Today (Revenue)</th>
                  <th className="px-6 py-4 text-left text-xs font-bold text-gray-400 uppercase tracking-wider">Month (Revenue)</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-50">
                {userStats.map((stat: any) => (
                  <tr key={stat.email} className="hover:bg-gray-50/50 transition-colors">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm font-bold text-gray-900">{stat.name || stat.email}</div>
                      <div className="text-xs text-gray-500">{stat.nick_name || '-'}</div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 font-black">{stat.today_count}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 font-black">{stat.month_count}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-emerald-600 font-black">PKR {stat.today_revenue || 0}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-emerald-600 font-black">PKR {stat.month_revenue || 0}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          
          {/* Pagination */}
          <div className="px-6 py-4 bg-gray-50/50 border-t border-gray-100 flex items-center justify-between">
            <div className="text-sm text-gray-500">
              Showing <span className="font-bold">{(userStatsPage - 1) * 20 + 1}</span> to <span className="font-bold">{Math.min(userStatsPage * 20, totalUserStats)}</span> of <span className="font-bold">{totalUserStats}</span> users
            </div>
            <div className="flex gap-2">
              <button 
                disabled={userStatsPage === 1}
                onClick={() => setUserStatsPage(prev => prev - 1)}
                className="px-4 py-2 bg-white border border-gray-200 rounded-xl text-sm font-bold disabled:opacity-50 hover:bg-gray-50 transition-all"
              >
                Previous
              </button>
              <button 
                disabled={userStatsPage * 20 >= totalUserStats}
                onClick={() => setUserStatsPage(prev => prev + 1)}
                className="px-4 py-2 bg-white border border-gray-200 rounded-xl text-sm font-bold disabled:opacity-50 hover:bg-gray-50 transition-all"
              >
                Next
              </button>
            </div>
          </div>
        </div>
      ) : (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
              <p className="text-xs font-bold text-gray-400 uppercase">Total Transactions</p>
              <p className="text-2xl font-black text-gray-900">{myReports.length}</p>
            </div>
            <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
              <p className="text-xs font-bold text-gray-400 uppercase">Total Tickets</p>
              <p className="text-2xl font-black text-indigo-600">{myReports.filter(r => r.ticket_id).length}</p>
            </div>
            <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
              <p className="text-xs font-bold text-gray-400 uppercase">Online Revenue</p>
              <p className="text-2xl font-black text-green-600">PKR {myReports.filter(r => r.payment_type === 'ONLINE').reduce((acc, curr) => acc + (curr.amount || 0), 0)}</p>
            </div>
            <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
              <p className="text-xs font-bold text-gray-400 uppercase">Cash Revenue</p>
              <p className="text-2xl font-black text-blue-600">PKR {myReports.filter(r => r.payment_type === 'CASH').reduce((acc, curr) => acc + (curr.amount || 0), 0)}</p>
            </div>
          </div>

          <div className="bg-white shadow-sm rounded-xl border border-gray-200 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Tx ID</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Ticket ID</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Amount</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Printed</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {myReports.map((report, idx) => (
                    <tr key={idx} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-mono text-gray-600">{report.tx_id}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-bold text-indigo-600">{report.ticket_id || '-'}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 font-medium">PKR {report.amount}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{new Date(report.date).toLocaleDateString()}</td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className={`px-2 py-1 text-[10px] font-bold rounded-full uppercase ${report.status === 'Generated' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'}`}>
                          {report.status}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {report.printed_count > 0 ? (
                          <CheckCircle className="w-4 h-4 text-green-500" />
                        ) : (
                          <XCircle className="w-4 h-4 text-gray-300" />
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Pagination */}
            <div className="px-6 py-4 bg-gray-50 border-t border-gray-200 flex items-center justify-between">
              <div className="text-sm text-gray-500">
                Showing <span className="font-medium">{(myReportsPage - 1) * 20 + 1}</span> to <span className="font-medium">{Math.min(myReportsPage * 20, totalMyReports)}</span> of <span className="font-medium">{totalMyReports}</span> transactions
              </div>
              <div className="flex space-x-2">
                <button 
                  disabled={myReportsPage === 1}
                  onClick={() => setMyReportsPage(prev => prev - 1)}
                  className="px-3 py-1 border border-gray-300 rounded-md text-sm disabled:opacity-50 bg-white"
                >
                  Previous
                </button>
                <button 
                  disabled={myReportsPage * 20 >= totalMyReports}
                  onClick={() => setMyReportsPage(prev => prev + 1)}
                  className="px-3 py-1 border border-gray-300 rounded-md text-sm disabled:opacity-50 bg-white"
                >
                  Next
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Customer Details Modal */}
      {selectedTicket && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full overflow-hidden">
            <div className="p-6 border-b border-gray-100 flex justify-between items-center bg-indigo-600 text-white">
              <h3 className="text-lg font-bold">Customer & Ticket Details</h3>
              <button onClick={() => setSelectedTicket(null)} className="text-white/80 hover:text-white text-2xl">&times;</button>
            </div>
            <div className="p-8 grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="space-y-6">
                <div>
                  <h4 className="text-[10px] uppercase font-bold text-gray-400 tracking-widest mb-2">Customer Information</h4>
                  <div className="bg-gray-50 rounded-xl p-4 space-y-3">
                    <div>
                      <p className="text-xs text-gray-500">Full Name</p>
                      <p className="text-sm font-semibold text-gray-900">{selectedTicket.name}</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-500">Mobile Number</p>
                      <p className="text-sm font-semibold text-gray-900">{selectedTicket.mobile}</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-500">Address</p>
                      <p className="text-sm font-semibold text-gray-900">{selectedTicket.address || 'N/A'}</p>
                    </div>
                  </div>
                </div>
                <div>
                  <h4 className="text-[10px] uppercase font-bold text-gray-400 tracking-widest mb-2">System Information</h4>
                  <div className="bg-gray-50 rounded-xl p-4 space-y-3">
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <p className="text-xs text-gray-500">Ticket ID</p>
                        <p className="text-sm font-mono font-bold text-indigo-600">{selectedTicket.ticket_id}</p>
                      </div>
                      <div>
                        <p className="text-xs text-gray-500">Generation ID</p>
                        <p className="text-sm font-mono text-gray-700">{selectedTicket.generation_id}</p>
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <p className="text-xs text-gray-500">Transaction ID</p>
                        <p className="text-sm font-mono text-gray-700">{selectedTicket.tx_id}</p>
                      </div>
                      <div>
                        <p className="text-xs text-gray-500">Date Generated</p>
                        <p className="text-sm text-gray-700">{new Date(selectedTicket.date).toLocaleString()}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="space-y-6">
                <div>
                  <h4 className="text-[10px] uppercase font-bold text-gray-400 tracking-widest mb-2">Audit & Tracking</h4>
                  <div className="bg-gray-50 rounded-xl p-4 space-y-3">
                    <div>
                      <p className="text-xs text-gray-500">Generated By</p>
                      <p className="text-sm font-semibold text-gray-900">{selectedTicket.generated_by_nick || selectedTicket.generated_by}</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-500">Last Printed By</p>
                      <p className="text-sm font-semibold text-gray-900">{selectedTicket.last_printed_by_nick || 'Not Printed Yet'}</p>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <p className="text-xs text-gray-500">Print Count</p>
                        <p className="text-sm font-bold text-orange-600">{selectedTicket.printed_count} times</p>
                      </div>
                      <div>
                        <p className="text-xs text-gray-500">Batch Info</p>
                        <p className="text-sm text-gray-700">{selectedTicket.person_ticket_index} of {selectedTicket.total_tickets_in_tx}</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="flex justify-center pt-4">
                  <div className="bg-white p-4 border-2 border-dashed border-gray-200 rounded-2xl">
                    <QRCodeSVG 
                      value={JSON.stringify({
                        id: selectedTicket.ticket_id,
                        name: selectedTicket.name,
                        tx: selectedTicket.tx_id,
                        gen: selectedTicket.generation_id
                      })}
                      size={120}
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="p-4 bg-gray-50 flex justify-end">
              <button 
                onClick={() => setSelectedTicket(null)}
                className="px-6 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50 shadow-sm"
              >
                Close Details
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
